name: PR Workflow and Deploy

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  #push:
    #branches:
      #- main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  
    if: github.ref == 'refs/heads/main'  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync ./ s3://${{ secrets.S3_BUCKET_NAME }}/ --delete

      - name: Verify files in S3
        run: aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive  
